name: Scrape Poker Games

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install libraries
        run: pip install -r requirements.txt

      - name: Run scraper
        run: |
  python npl_scraper.py
  python kings_scraper.py

      - name: Commit JSON
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add npl_games.json
          git commit -m "update poker data" || echo "no changes"
          git push
